### ISSUE TITLE
Возможно ли поднять прокси сервер без настройки роутера?

### ISSUE THREAD

**Issue by ghost** [fdsc/vinny-socks5-proxy#1]
Возможно ли поднять прокси сервер к которому можно будет подключиться с внешнего адреса без настройки роутера?
Код работает, но только для локалхоста. Порты в фаерволе открыты.

**Comment by fdsc** [comment]
Если у вас на роутере трансляция адресов, то - невозможно. Прокси не умеет использовать uPnP, так что даже если uPnP включён на роутере, именно этот прокси не сможет это сделать.

Теоретически, у вас на роутере уже могут быть проброшены открытые входящие порты, но это вряд ли.

**Comment by fdsc** [comment]
По факту, роутер тоже является межсетевым экраном (фаерволом), поэтому, он может вообще блокировать все входящие.

P.S. Если помощь больше не нужна, пожалуйста, закройте эту ветку. Если есть ещё вопросы - задавайте.

**Comment by ghost** [comment]
Спасибо. Дело в том что я видел систему которая как-то поднимала прокси сервер к которому можно было сразу подключиться с внешнего адреса.

**Comment by fdsc** [comment]
Из того, что мне приходит в голову
1. Роутер был уже настроен и имел открытые входящие порты.
2. Роутер имел uPnP или другую аналогичную включённую технологию и прокси сам настраивал роутер
3. Роутер был полностью прозрачным, то есть перенаправлял все запросы с внешнего IP на какой-то внутренний IP
4. Была поднята какая-то система обхода NAT через сторонний координирующий сервер.

Других возможностей лично я не вижу. Мой прокси ничего этого не умеет.

А почему вы не можете настроить роутер?

**Comment by ghost** [comment]
Нет такой возможности. Спасибо.

**Comment by fdsc** [comment]
Попробуйте поискать открытые порты. Возможно, роутер пробрасывает какой-то входящий порт к вам на IP-адрес. Например, 80-ый, 8080 или 3128.
Хотя вероятность низка, что там что-то открыто. А если это роутер интернет-провайдера, то он, скорее всего, вообще блокирует все входящие.
